### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by aymanbagabas** [danielgatis/go-vte#2]
Hi @danielgatis

Thank you for this awesome port of an amazing library. Since the latest changes were breaking, could you make a new release so we can pin applications to a specific version?

**Comment by danielgatis** [comment]
@aymanbagabas sure, do you mind to teach how to do it?

**Comment by aymanbagabas** [comment]
You could draft a new release on GitHub and specify a tag in the Semver version number format with a `v` prefix like `v0.1.2` 🙂

**Comment by danielgatis** [comment]
done!

**Comment by danielgatis** [comment]
@aymanbagabas i think you gonna like this project too: https://github.com/danielgatis/go-ansicode ;)
